apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofbiz
  namespace: demo
spec:
  selector:
    matchLabels:
      app: ofbiz
  template:
    metadata:
      labels:
        app: ofbiz
    spec:
      containers:
        - name: ofbiz
          image: safeeraccuknox/demo:CVE-2024-38856-POC
          ports:
            - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: ofbiz
  namespace: demo
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: ofbiz
